manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ivyp
      url-base: https://github.com/ivyp
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-bongocat-widget
      remote: ivyp
      revision: master
  self:
    path: config
